version: '3.3'

services:

  db:
    restart: always
    container_name: mlflow_db
    expose:
      - "3306"

  mlflow-server:
    restart: always
    image: mlflow_server
    container_name: mlflow_server
    expose:
      - "5000"
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DATABASE} --default-artifact-root s3://mlflow_bucket/mlflow/ --host 0.0.0.0